version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - app-network

  file-storing-service:
    build:
      context: FileStoringService/
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      # - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=FileStorageDb;Username=postgres;Password=password
    volumes:
      - files_storage:/app/Files
    networks:
      - app-network

  file-analysis-service:
    build:
      context: FileAnalysisService/
      dockerfile: Dockerfile
    depends_on:
      - db
      - file-storing-service
    ports:
      - "5001:5001" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      # - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=FileAnalysisDb;Username=postgres;Password=password
      # - FileStoringService__BaseUrl=http://file-storing-service:5000
    volumes:
      - files_analysis:/app/analysis
    networks:
      - app-network

  api-gateway:
    build:
      context: APIGateway/
      dockerfile: Dockerfile
    depends_on:
      - file-analysis-service
      - file-storing-service
    ports:
      - "5002:5002" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      # - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=FileAnalysisDb;Username=postgres;Password=password
      # - FileStoringService__BaseUrl=http://file-storing-service:5000
    networks:
      - app-network

volumes:
  postgres_data:
  files_storage:
  files_analysis:
networks:
  app-network:
    driver: bridge
